### ISSUE TITLE
Human Companions Dawncraft Tweaks Easter Egg Hangs Server World Generation

### ISSUE THREAD

**Issue by Davoleo** [SmileycorpMC/DawnCraft-Tweaks#3] opened 2023-07-20 15:03 UTC
@PierKnight and I have been investigating some crash reports and logs after server hang watchdogs when using the `chunky` pregenerator. 

- We excluded the problem being a memory leak / out of memory issue as we both tried on our small VPS and on our local computers.
- We excluded the problem being on an outdated version of Dawncraft only since we both tested on the version we use on our VPS [1.24 patched with BetterDawncraft] and on the latest 1.26
- We excluded the problem being a Chunky pregenerator problem because we also tried the  Chunk-Pregenerator mod by Speiger

Reading into the stacktraces we realized this mod is actually causing the server crash when replacing the spawn of a human companion with a custom one in world, more precisely on this line: https://github.com/SmileycorpMC/DawnCraft-Tweaks/blob/master/src/main/java/com/afunproject/dawncraft/integration/humancompanions/HCEvents.java#L48
We don't know how precisely that becomes a vanilla IndexOutOfBound issue but since part of this feature is just an _easter egg_ it would be cool if it was hotfixed and disabled or at least able to be disabled via config while an actual fix of the problem is developed.

We also found a stacktrace call that references this class: https://github.com/SmileycorpMC/DawnCraft-Tweaks/blob/master/src/main/java/com/afunproject/dawncraft/integration/dcmobs/SimpleMobsEvents.java
Not sure how related it is, but it might give more insight, I'll also share some of the crash reports.

Crash Report [dedicated server]: [crash-2023-07-20_15.37.30-server.txt](https://github.com/SmileycorpMC/DawnCraft-Tweaks/files/12110898/crash-2023-07-20_15.37.30-server.txt)
Crash Report [integrated server]: [message.txt](https://github.com/SmileycorpMC/DawnCraft-Tweaks/files/12110899/message.txt)

**Comment by SmileycorpMC** [comment] 2023-07-22 12:10
Firstly I'd recommend disabling server watchdog in the forge config, this modpack has a few issues that can cause it,

Secondly, as it's one of our patron rewards I can't disable the functionality, but I will have a look at why it's crashing, and why it's causing ticks to take so long or crashing and see if that's fixable, or potentially if there's another way to do it. 
From looking at the method, the line that's mentioned is the only line of it that could potentially cause issue, so I'll see if there's ways around it.

**Comment by Davoleo** [comment] 2023-07-22 12:44
We've already tried disabling the server watchdog before, the result is the same though, the server thread just freezes and the only way out of it is to kill the process entirely, which btw also doesn't give any crash-report so in this case watchdog actually helped tracking down the cause.

Thanks for your time to investigate.
Since the issue is quite serious and a bit frustrating when trying to pregenerate worlds is creating a config option for it that unfeasible? even if it's a Patreon feature, we could disable it for our instance specifically and other users that are not interested in those rewards could do it as well, while still keeping the default value to enabled, at least to temporarily fix this crash?

**Comment by Shybella** [comment] 2023-07-31 17:01
Experiencing this now 

log: https://pastebin.com/raw/HC5B48sg

Disabling watchdog does not stop this from happening.

**Comment by Shybella** [comment] 2023-07-31 17:11
What can be done or a quick solution? I removed Humancompanions but that does not solve the issue because the issue doesn't occur in that mod, used BadMobs to disable knights from spawning but issue will occurs. 

I have no issues with supporting you on Patreon, I just need the fix if I do that. Thanks 

I was just going to recompile this mod with https://github.com/SmileycorpMC/DawnCraft-Tweaks/blob/master/src/main/java/com/afunproject/dawncraft/integration/humancompanions/HCEvents.java#L48 just removed and continue pregeneration, I just didn't want another mod to manage.

**Comment by Shybella** [comment] 2023-08-01 17:36
What's the point of having an issues section if it just gets ignored??

**Comment by SettingDust** [comment] 2023-12-16 04:58
> What's the point of having an issues section if it just gets ignored??

@Shybella 
Be patient and polite. It's a free and open-source project under an MIT license(https://github.com/SmileycorpMC/DawnCraft-Tweaks/blob/master/LICENSE). No one has the liability or warranty to pick up your issue.

Your log is truncated and not a crash report. 

For this issue. As the original post said

> Not sure how related it is

It's not enough to prove the line causes it. I think a spark profile is helpful. It's just stuck at getting chunks from the world.
The server watchdog only shows the stack trace when the tick achieves the throttle. Not all the tick is running for the stack trace.

**Comment by Shybella** [comment] 2023-12-16 18:36
> > What's the point of having an issues section if it just gets ignored??
> 
> @Shybella Be patient and polite. It's a free and open-source project under an MIT license(https://github.com/SmileycorpMC/DawnCraft-Tweaks/blob/master/LICENSE). No one has the liability or warranty to pick up your issue.
> 
> Your log is truncated and not a crash report.
> 
> For this issue. As the original post said
> 
> > Not sure how related it is
> 
> It's not enough to prove the line causes it. I think a spark profile is helpful. It's just stuck at getting chunks from the world. The server watchdog only shows the stack trace when the tick achieves the throttle. Not all the tick is running for the stack trace.

This is a joke, right? Have you not seen OPs post? You cannot even generate a world for more than 5 minutes without the crash happening, its super easy to reproduce with chunky. 

It's actually insane because the issue has way above average debug data than you'd find on average and enough fingers pointing at what the problem is and yet still an excuse. 

Lazyboneitus, even if a PR was made it would be ignored.

**Comment by SmileycorpMC** [comment] 2023-12-16 23:57
The issue is already fixed, I'm just waiting on the pack to update.

**Comment by SettingDust** [comment] 2023-12-17 09:44
> This is a joke, right? Have you not seen OPs post? You cannot even generate a world for more than 5 minutes without the crash happening, its super easy to reproduce with chunky.

Where is the logic?

> Lazyboneitus, even if a PR was made it would be ignored.

Where is the PR?

**Comment by Shybella** [comment] 2024-03-04 21:24
Any update? It's been a few months

**Comment by SmileycorpMC** [comment] 2024-03-04 23:10
Pack should hopefully be updating soon, unfortunatley I don't have any control on when the actual pack updates.

**Comment by Shybella** [comment] 2024-03-04 23:17
> Pack should hopefully be updating soon, unfortunatley I don't have any control on when the actual pack updates.

thanks for the response and hard work

**Comment by Shybella** [comment] 2024-03-11 04:55
amazing update, this is fixed now

**Comment by SmileycorpMC** [comment] 2024-03-11 12:37
Sorry it took so long for the release to come out and fix the issue.

**Closed as completed by SmileycorpMC** 2024-03-11 12:37 UTC
